-- =====================================================
-- Poultry Management System - Sample Data
-- =====================================================
-- Run this AFTER running poultry_complete_schema.sql and poultry_rls_policies.sql
-- This inserts sample/test data for testing the Poultry Module
-- =====================================================

-- IMPORTANT: Replace the farm_id UUIDs below with actual farm IDs from your farms table
-- You can get them by running: SELECT id, name FROM farms;

-- =====================================================
-- STEP 1: Get your farm IDs first
-- =====================================================
-- Uncomment and run this to see your farms:
-- SELECT id, name, type FROM farms WHERE type IN ('Broiler', 'Layer', 'Mixed');

-- =====================================================
-- STEP 2: Update the farm_id values below
-- =====================================================
-- Replace 'YOUR_FARM_ID_1' and 'YOUR_FARM_ID_2' with actual UUIDs from your farms table

-- For this example, we'll use variables (you'll need to replace these)
-- In Supabase, you can use: SELECT id FROM farms LIMIT 1; to get a farm ID

-- =====================================================
-- POULTRY HOUSES
-- =====================================================

-- Insert sample poultry houses
-- Note: Replace 'YOUR_FARM_ID_1' with an actual farm ID
INSERT INTO poultry_houses (farm_id, name, capacity, house_type, notes)
VALUES 
  -- Replace 'YOUR_FARM_ID_1' with actual farm UUID
  ((SELECT id FROM farms WHERE type IN ('Broiler', 'Layer', 'Mixed') LIMIT 1), 'House A - Broilers', 5000, 'Broiler House', 'Main broiler house with automated feeding'),
  ((SELECT id FROM farms WHERE type IN ('Broiler', 'Layer', 'Mixed') LIMIT 1), 'House B - Layers', 3000, 'Layer House', 'Layer house with nest boxes'),
  ((SELECT id FROM farms WHERE type IN ('Broiler', 'Layer', 'Mixed') LIMIT 1), 'House C - Mixed', 4000, 'Mixed', 'Mixed production house')
ON CONFLICT DO NOTHING;

-- =====================================================
-- POULTRY BATCHES
-- =====================================================

-- Insert sample batches (both Broiler and Layer)
-- The batch_flock_id will be auto-generated by the trigger

-- Insert Broiler batch
INSERT INTO poultry_batches (
  production_type, farm_id, house_id, breed_strain, source, 
  placement_date, initial_quantity, age_at_placement, 
  production_phase, expected_market_date, expected_laying_period, status, notes
)
SELECT 
  'Broiler' as production_type,
  f.id as farm_id,
  ph.id as house_id,
  'Cobb 500' as breed_strain,
  'ABC Hatchery' as source,
  CURRENT_DATE - INTERVAL '25 days' as placement_date,
  4500 as initial_quantity,
  NULL as age_at_placement,
  NULL as production_phase,
  CURRENT_DATE + INTERVAL '5 days' as expected_market_date,
  NULL as expected_laying_period,
  'Active' as status,
  'First broiler batch - monitoring closely' as notes
FROM farms f
CROSS JOIN poultry_houses ph
WHERE f.type IN ('Broiler', 'Mixed')
  AND ph.house_type IN ('Broiler House', 'Mixed')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Insert Layer batch
INSERT INTO poultry_batches (
  production_type, farm_id, house_id, breed_strain, source, 
  placement_date, initial_quantity, age_at_placement, 
  production_phase, expected_market_date, expected_laying_period, status, notes
)
SELECT 
  'Layer' as production_type,
  f.id as farm_id,
  ph.id as house_id,
  'Lohmann Brown' as breed_strain,
  'XYZ Poultry Farm' as source,
  CURRENT_DATE - INTERVAL '120 days' as placement_date,
  2800 as initial_quantity,
  18 as age_at_placement,
  'Layer' as production_phase,
  NULL as expected_market_date,
  365 as expected_laying_period,
  'Active' as status,
  'Layer flock - peak production phase' as notes
FROM farms f
CROSS JOIN poultry_houses ph
WHERE f.type IN ('Layer', 'Mixed')
  AND ph.house_type IN ('Layer House', 'Mixed')
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- BATCH STOCK MOVEMENTS
-- =====================================================

-- Insert sample daily stock movements for the last 7 days
-- Using generate_series for cleaner date generation
INSERT INTO batch_stock_movements (batch_id, date, opening_stock, mortalities, culls, notes)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - (day_offset) as date,
  pb.initial_quantity - (day_offset * 2) as opening_stock,
  1 + (random() * 3)::INTEGER as mortalities,
  (random() * 2)::INTEGER as culls,
  'Daily stock check' as notes
FROM poultry_batches pb
CROSS JOIN generate_series(0, 6) as day_offset
WHERE pb.status = 'Active'
  AND NOT EXISTS (
    SELECT 1 FROM batch_stock_movements bsm 
    WHERE bsm.batch_id = pb.id 
    AND bsm.date = CURRENT_DATE - day_offset
  );

-- =====================================================
-- FEED ISSUANCE
-- =====================================================

-- Insert sample feed issuance records
-- Recent feed issuance
INSERT INTO feed_issuance (
  batch_id, feed_type, supplier, issuance_date, quantity_kg, 
  quantity_bags, bags_per_kg, unit_cost, notes
)
SELECT 
  pb.id as batch_id,
  CASE WHEN pb.production_type = 'Broiler' THEN 'Starter Feed' ELSE 'Layer Feed' END as feed_type,
  'Feed Suppliers Ltd' as supplier,
  CURRENT_DATE - INTERVAL '2 days' as issuance_date,
  500.00 as quantity_kg,
  10 as quantity_bags,
  50 as bags_per_kg,
  45.00 as unit_cost,
  'Regular feed issuance' as notes
FROM poultry_batches pb
WHERE pb.status = 'Active'
ON CONFLICT DO NOTHING;

-- Previous feed issuance
INSERT INTO feed_issuance (
  batch_id, feed_type, supplier, issuance_date, quantity_kg, 
  quantity_bags, bags_per_kg, unit_cost, notes
)
SELECT 
  pb.id as batch_id,
  CASE WHEN pb.production_type = 'Broiler' THEN 'Grower Feed' ELSE 'Layer Feed' END as feed_type,
  'Feed Suppliers Ltd' as supplier,
  CURRENT_DATE - INTERVAL '5 days' as issuance_date,
  750.00 as quantity_kg,
  15 as quantity_bags,
  50 as bags_per_kg,
  42.00 as unit_cost,
  'Previous feed issuance' as notes
FROM poultry_batches pb
WHERE pb.status = 'Active'
ON CONFLICT DO NOTHING;

-- =====================================================
-- VACCINATIONS
-- =====================================================

-- Insert sample vaccination records
-- First vaccination (Newcastle Disease)
INSERT INTO vaccinations (
  batch_id, vaccination_date, birds_age_days, vaccine_name, disease_target,
  administration_method, dosage, number_of_birds, manufacturer, batch_number,
  expiry_date, cost_per_dosage, veterinary_name, status, notes
)
SELECT 
  pb.id as batch_id,
  pb.placement_date + INTERVAL '7 days' as vaccination_date,
  7 as birds_age_days,
  'Newcastle Disease Vaccine' as vaccine_name,
  'Newcastle Disease' as disease_target,
  'Water' as administration_method,
  '1ml per liter' as dosage,
  pb.initial_quantity as number_of_birds,
  'VetPharm Ltd' as manufacturer,
  'ND-2024-001' as batch_number,
  CURRENT_DATE + INTERVAL '6 months' as expiry_date,
  0.50 as cost_per_dosage,
  'Dr. John Smith' as veterinary_name,
  'Completed' as status,
  'First vaccination - Newcastle Disease' as notes
FROM poultry_batches pb
WHERE pb.status = 'Active'
ON CONFLICT DO NOTHING;

-- Second vaccination (Gumboro)
INSERT INTO vaccinations (
  batch_id, vaccination_date, birds_age_days, vaccine_name, disease_target,
  administration_method, dosage, number_of_birds, manufacturer, batch_number,
  expiry_date, cost_per_dosage, veterinary_name, status, notes
)
SELECT 
  pb.id as batch_id,
  pb.placement_date + INTERVAL '14 days' as vaccination_date,
  14 as birds_age_days,
  'Gumboro Vaccine' as vaccine_name,
  'Gumboro Disease' as disease_target,
  'Water' as administration_method,
  '1ml per liter' as dosage,
  pb.initial_quantity - 10 as number_of_birds,
  'VetPharm Ltd' as manufacturer,
  'GB-2024-001' as batch_number,
  CURRENT_DATE + INTERVAL '6 months' as expiry_date,
  0.45 as cost_per_dosage,
  'Dr. John Smith' as veterinary_name,
  'Completed' as status,
  'Second vaccination - Gumboro' as notes
FROM poultry_batches pb
WHERE pb.status = 'Active'
ON CONFLICT DO NOTHING;

-- =====================================================
-- POULTRY MEDICATIONS
-- =====================================================

-- Insert sample medication records
INSERT INTO poultry_medications (
  batch_id, treatment_date, medication_name, disease_condition,
  administration_method, dosage, number_of_birds, withdrawal_period_days,
  cost, veterinary_name, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '10 days' as treatment_date,
  'Amoxicillin' as medication_name,
  'Respiratory Infection' as disease_condition,
  'Water' as administration_method,
  '500mg per liter' as dosage,
  pb.initial_quantity - 50 as number_of_birds,
  7 as withdrawal_period_days,
  150.00 as cost,
  'Dr. Jane Doe' as veterinary_name,
  'Treatment for respiratory symptoms' as notes
FROM poultry_batches pb
WHERE pb.status = 'Active'
LIMIT 1

ON CONFLICT DO NOTHING;

-- =====================================================
-- EGG COLLECTIONS ENHANCED
-- =====================================================

-- Insert sample egg collection records (for layer batches only)
-- Recent egg collection
INSERT INTO egg_collections_enhanced (
  batch_id, farm_id, collection_date, collection_time, total_eggs_collected,
  grade_a_quantity, grade_b_quantity, grade_c_quantity, dirty_eggs_quantity,
  average_egg_weight_g, storage_temperature_c, notes
)
SELECT 
  pb.id as batch_id,
  pb.farm_id as farm_id,
  CURRENT_DATE - INTERVAL '1 day' as collection_date,
  '08:00:00'::TIME as collection_time,
  2450 as total_eggs_collected,
  2000 as grade_a_quantity,
  350 as grade_b_quantity,
  80 as grade_c_quantity,
  20 as dirty_eggs_quantity,
  58.5 as average_egg_weight_g,
  18.0 as storage_temperature_c,
  'Morning collection - good quality' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Layer' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- Previous egg collection
INSERT INTO egg_collections_enhanced (
  batch_id, farm_id, collection_date, collection_time, total_eggs_collected,
  grade_a_quantity, grade_b_quantity, grade_c_quantity, dirty_eggs_quantity,
  average_egg_weight_g, storage_temperature_c, notes
)
SELECT 
  pb.id as batch_id,
  pb.farm_id as farm_id,
  CURRENT_DATE - INTERVAL '2 days' as collection_date,
  '08:30:00'::TIME as collection_time,
  2380 as total_eggs_collected,
  1950 as grade_a_quantity,
  320 as grade_b_quantity,
  90 as grade_c_quantity,
  20 as dirty_eggs_quantity,
  57.8 as average_egg_weight_g,
  18.5 as storage_temperature_c,
  'Previous day collection' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Layer' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- BROILER PRODUCTION
-- =====================================================

-- Insert sample broiler production records
-- Recent production
INSERT INTO broiler_production (
  batch_id, date, average_weight_kg, daily_gain_kg, total_feed_consumed_kg,
  mortality_count, current_count, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '1 day' as date,
  2.1 as average_weight_kg,
  0.05 as daily_gain_kg,
  450.00 as total_feed_consumed_kg,
  2 as mortality_count,
  pb.initial_quantity - 15 as current_count,
  'Daily production record - good growth rate' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Broiler' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- Previous production
INSERT INTO broiler_production (
  batch_id, date, average_weight_kg, daily_gain_kg, total_feed_consumed_kg,
  mortality_count, current_count, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '2 days' as date,
  2.05 as average_weight_kg,
  0.05 as daily_gain_kg,
  420.00 as total_feed_consumed_kg,
  1 as mortality_count,
  pb.initial_quantity - 13 as current_count,
  'Previous day production' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Broiler' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- LAYER PRODUCTION
-- =====================================================

-- Insert sample layer production records
-- Recent production
INSERT INTO layer_production (
  batch_id, date, eggs_per_bird, production_percentage, total_eggs,
  current_bird_count, feed_consumed_kg, feed_cost_per_egg, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '1 day' as date,
  0.88 as eggs_per_bird,
  88.0 as production_percentage,
  2450 as total_eggs,
  2785 as current_bird_count,
  350.00 as feed_consumed_kg,
  0.14 as feed_cost_per_egg,
  'Good production rate - peak laying' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Layer' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- Previous production
INSERT INTO layer_production (
  batch_id, date, eggs_per_bird, production_percentage, total_eggs,
  current_bird_count, feed_consumed_kg, feed_cost_per_egg, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '2 days' as date,
  0.85 as eggs_per_bird,
  85.0 as production_percentage,
  2380 as total_eggs,
  2790 as current_bird_count,
  345.00 as feed_consumed_kg,
  0.145 as feed_cost_per_egg,
  'Previous day production' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Layer' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- CUSTOMERS
-- =====================================================

-- Insert sample customers
-- Note: customer_code will be auto-generated by trigger
-- Handle both old (ecommerce) and new (poultry) table structures
-- First customer
INSERT INTO customers (
  email, full_name, phone, address, city, county,
  customer_name, contact_phone, contact_email,
  customer_type, payment_terms, is_active
)
SELECT 
  'info@greenmarket.co.ke' as email,
  'Green Market Stores' as full_name,
  '+254712345678' as phone,
  'Nairobi, Kenya' as address,
  'Nairobi' as city,
  'Nairobi' as county,
  'Green Market Stores' as customer_name,
  '+254712345678' as contact_phone,
  'info@greenmarket.co.ke' as contact_email,
  'Retail' as customer_type,
  'Net 30' as payment_terms,
  true as is_active
WHERE NOT EXISTS (
  SELECT 1 FROM customers 
  WHERE email = 'info@greenmarket.co.ke' 
     OR COALESCE(customer_name, full_name) = 'Green Market Stores'
)
ON CONFLICT (email) DO NOTHING;

-- Update notes if column exists
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'customers' AND column_name = 'notes'
  ) THEN
    UPDATE customers 
    SET notes = 'Regular customer - weekly orders' 
    WHERE email = 'info@greenmarket.co.ke'
    AND (notes IS NULL OR notes = '');
  END IF;
END $$;

-- Second customer
INSERT INTO customers (
  email, full_name, phone, address, city, county,
  customer_name, contact_phone, contact_email,
  customer_type, payment_terms, is_active
)
SELECT 
  'sales@fresheggs.co.ke' as email,
  'Fresh Eggs Distributors' as full_name,
  '+254723456789' as phone,
  'Mombasa, Kenya' as address,
  'Mombasa' as city,
  'Mombasa' as county,
  'Fresh Eggs Distributors' as customer_name,
  '+254723456789' as contact_phone,
  'sales@fresheggs.co.ke' as contact_email,
  'Wholesale' as customer_type,
  'Net 15' as payment_terms,
  true as is_active
WHERE NOT EXISTS (
  SELECT 1 FROM customers 
  WHERE email = 'sales@fresheggs.co.ke' 
     OR COALESCE(customer_name, full_name) = 'Fresh Eggs Distributors'
)
ON CONFLICT (email) DO NOTHING;

-- Update notes if column exists
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'customers' AND column_name = 'notes'
  ) THEN
    UPDATE customers 
    SET notes = 'Bulk egg distributor' 
    WHERE email = 'sales@fresheggs.co.ke'
    AND (notes IS NULL OR notes = '');
  END IF;
END $$;

-- Third customer
INSERT INTO customers (
  email, full_name, phone, address, city, county,
  customer_name, contact_phone, contact_email,
  customer_type, payment_terms, is_active
)
SELECT 
  'orders@ppl.co.ke' as email,
  'Poultry Products Ltd' as full_name,
  '+254734567890' as phone,
  'Kisumu, Kenya' as address,
  'Kisumu' as city,
  'Kisumu' as county,
  'Poultry Products Ltd' as customer_name,
  '+254734567890' as contact_phone,
  'orders@ppl.co.ke' as contact_email,
  'Distributor' as customer_type,
  'Net 45' as payment_terms,
  true as is_active
WHERE NOT EXISTS (
  SELECT 1 FROM customers 
  WHERE email = 'orders@ppl.co.ke' 
     OR COALESCE(customer_name, full_name) = 'Poultry Products Ltd'
)
ON CONFLICT (email) DO NOTHING;

-- Update notes if column exists
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'customers' AND column_name = 'notes'
  ) THEN
    UPDATE customers 
    SET notes = 'Large distributor - monthly orders' 
    WHERE email = 'orders@ppl.co.ke'
    AND (notes IS NULL OR notes = '');
  END IF;
END $$;

-- Fourth customer
INSERT INTO customers (
  email, full_name, phone, address, city, county,
  customer_name, contact_phone, contact_email,
  customer_type, payment_terms, is_active
)
SELECT 
  'procurement@restaurant.co.ke' as email,
  'Local Restaurant Chain' as full_name,
  '+254745678901' as phone,
  'Nakuru, Kenya' as address,
  'Nakuru' as city,
  'Nakuru' as county,
  'Local Restaurant Chain' as customer_name,
  '+254745678901' as contact_phone,
  'procurement@restaurant.co.ke' as contact_email,
  'Retail' as customer_type,
  'Cash on Delivery' as payment_terms,
  true as is_active
WHERE NOT EXISTS (
  SELECT 1 FROM customers 
  WHERE email = 'procurement@restaurant.co.ke' 
     OR COALESCE(customer_name, full_name) = 'Local Restaurant Chain'
)
ON CONFLICT (email) DO NOTHING;

-- Update notes if column exists
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'customers' AND column_name = 'notes'
  ) THEN
    UPDATE customers 
    SET notes = 'Local restaurant - daily orders' 
    WHERE email = 'procurement@restaurant.co.ke'
    AND (notes IS NULL OR notes = '');
  END IF;
END $$;

-- =====================================================
-- BROILER SALES
-- =====================================================

-- Insert sample broiler sales
INSERT INTO broiler_sales (
  batch_id, sale_date, quantity, average_weight_kg, total_weight_kg,
  unit_price, total_amount, customer_id, customer_name, payment_method,
  payment_status, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '3 days' as sale_date,
  200 as quantity,
  2.0 as average_weight_kg,
  400.00 as total_weight_kg,
  350.00 as unit_price,
  140000.00 as total_amount,
  (SELECT id FROM customers WHERE COALESCE(customer_name, full_name) = 'Poultry Products Ltd' OR COALESCE(contact_email, email) = 'orders@ppl.co.ke' LIMIT 1) as customer_id,
  'Poultry Products Ltd' as customer_name,
  'Bank Transfer' as payment_method,
  'Fully Paid' as payment_status,
  'Bulk sale to distributor' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Broiler' AND pb.status = 'Active'
LIMIT 1

ON CONFLICT DO NOTHING;

-- =====================================================
-- LAYER SALES
-- =====================================================

-- Insert sample layer sales (eggs)
-- Recent sale
INSERT INTO layer_sales (
  batch_id, sale_date, product_type, quantity, unit, unit_price,
  total_amount, customer_id, customer_name, payment_method, payment_status, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '1 day' as sale_date,
  'Eggs' as product_type,
  2000 as quantity,
  'eggs' as unit,
  15.00 as unit_price,
  30000.00 as total_amount,
  (SELECT id FROM customers WHERE COALESCE(customer_name, full_name) = 'Fresh Eggs Distributors' OR COALESCE(contact_email, email) = 'sales@fresheggs.co.ke' LIMIT 1) as customer_id,
  'Fresh Eggs Distributors' as customer_name,
  'M-Pesa' as payment_method,
  'Fully Paid' as payment_status,
  'Grade A eggs sale' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Layer' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- Previous sale
INSERT INTO layer_sales (
  batch_id, sale_date, product_type, quantity, unit, unit_price,
  total_amount, customer_id, customer_name, payment_method, payment_status, notes
)
SELECT 
  pb.id as batch_id,
  CURRENT_DATE - INTERVAL '2 days' as sale_date,
  'Eggs' as product_type,
  1500 as quantity,
  'eggs' as unit,
  15.00 as unit_price,
  22500.00 as total_amount,
  (SELECT id FROM customers WHERE COALESCE(customer_name, full_name) = 'Green Market Stores' OR COALESCE(contact_email, email) = 'info@greenmarket.co.ke' LIMIT 1) as customer_id,
  'Green Market Stores' as customer_name,
  'Cash' as payment_method,
  'Fully Paid' as payment_status,
  'Retail egg sale' as notes
FROM poultry_batches pb
WHERE pb.production_type = 'Layer' AND pb.status = 'Active'
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- POULTRY ORDERS
-- =====================================================

-- Insert sample orders
-- Note: order_reference will be auto-generated
-- First order
INSERT INTO poultry_orders (
  customer_id, order_date, delivery_date, status, total_amount, notes
)
SELECT 
  c.id as customer_id,
  CURRENT_DATE - INTERVAL '5 days' as order_date,
  CURRENT_DATE + INTERVAL '2 days' as delivery_date,
  'Confirmed' as status,
  45000.00 as total_amount,
  'Order for 3000 eggs - confirmed' as notes
FROM customers c
WHERE (COALESCE(c.customer_name, c.full_name) = 'Fresh Eggs Distributors' OR COALESCE(c.contact_email, c.email) = 'sales@fresheggs.co.ke')
LIMIT 1
ON CONFLICT DO NOTHING;

-- Second order
INSERT INTO poultry_orders (
  customer_id, order_date, delivery_date, status, total_amount, notes
)
SELECT 
  c.id as customer_id,
  CURRENT_DATE - INTERVAL '2 days' as order_date,
  CURRENT_DATE + INTERVAL '1 day' as delivery_date,
  'Pending' as status,
  25000.00 as total_amount,
  'Order for 1500 eggs - pending confirmation' as notes
FROM customers c
WHERE (COALESCE(c.customer_name, c.full_name) = 'Green Market Stores' OR COALESCE(c.contact_email, c.email) = 'info@greenmarket.co.ke')
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- POULTRY ORDER ITEMS
-- =====================================================

-- Insert sample order items
-- First order item
INSERT INTO poultry_order_items (
  order_id, item_type, item_name, quantity, unit, unit_price, total_price, batch_id, notes
)
SELECT 
  po.id as order_id,
  'Eggs' as item_type,
  'Grade A Eggs' as item_name,
  3000 as quantity,
  'eggs' as unit,
  15.00 as unit_price,
  45000.00 as total_price,
  (SELECT id FROM poultry_batches WHERE production_type = 'Layer' LIMIT 1) as batch_id,
  'Premium grade eggs' as notes
FROM poultry_orders po
WHERE po.status = 'Confirmed'
LIMIT 1
ON CONFLICT DO NOTHING;

-- Second order item
INSERT INTO poultry_order_items (
  order_id, item_type, item_name, quantity, unit, unit_price, total_price, batch_id, notes
)
SELECT 
  po.id as order_id,
  'Eggs' as item_type,
  'Grade A Eggs' as item_name,
  1500 as quantity,
  'eggs' as unit,
  15.00 as unit_price,
  22500.00 as total_price,
  (SELECT id FROM poultry_batches WHERE production_type = 'Layer' LIMIT 1) as batch_id,
  'Standard order' as notes
FROM poultry_orders po
WHERE po.status = 'Pending'
LIMIT 1
ON CONFLICT DO NOTHING;

-- =====================================================
-- CHART OF ACCOUNTS
-- =====================================================

-- Insert sample chart of accounts
INSERT INTO chart_of_accounts (
  account_code, account_name, account_type, parent_account_id, notes, is_active
)
VALUES 
  ('1000', 'Assets', 'Asset', NULL, 'Main asset account', true),
  ('1100', 'Current Assets', 'Asset', (SELECT id FROM chart_of_accounts WHERE account_code = '1000' LIMIT 1), 'Current assets category', true),
  ('1110', 'Cash', 'Asset', (SELECT id FROM chart_of_accounts WHERE account_code = '1100' LIMIT 1), 'Cash account', true),
  ('1120', 'Accounts Receivable', 'Asset', (SELECT id FROM chart_of_accounts WHERE account_code = '1100' LIMIT 1), 'Receivables from customers', true),
  ('4000', 'Revenue', 'Revenue', NULL, 'Main revenue account', true),
  ('4100', 'Sales Revenue', 'Revenue', (SELECT id FROM chart_of_accounts WHERE account_code = '4000' LIMIT 1), 'Sales revenue category', true),
  ('4110', 'Egg Sales', 'Revenue', (SELECT id FROM chart_of_accounts WHERE account_code = '4100' LIMIT 1), 'Revenue from egg sales', true),
  ('4120', 'Broiler Sales', 'Revenue', (SELECT id FROM chart_of_accounts WHERE account_code = '4100' LIMIT 1), 'Revenue from broiler sales', true),
  ('5000', 'Expenses', 'Expense', NULL, 'Main expense account', true),
  ('5100', 'Operating Expenses', 'Expense', (SELECT id FROM chart_of_accounts WHERE account_code = '5000' LIMIT 1), 'Operating expenses category', true),
  ('5110', 'Feed Costs', 'Expense', (SELECT id FROM chart_of_accounts WHERE account_code = '5100' LIMIT 1), 'Feed and feed-related costs', true),
  ('5120', 'Veterinary Costs', 'Expense', (SELECT id FROM chart_of_accounts WHERE account_code = '5100' LIMIT 1), 'Vaccination and medication costs', true)
ON CONFLICT (account_code) DO NOTHING;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Run these queries to verify the data was inserted:

-- SELECT COUNT(*) as poultry_houses_count FROM poultry_houses;
-- SELECT COUNT(*) as batches_count FROM poultry_batches;
-- SELECT COUNT(*) as customers_count FROM customers;
-- SELECT COUNT(*) as orders_count FROM poultry_orders;
-- SELECT COUNT(*) as accounts_count FROM chart_of_accounts;

-- View all batches with their details:
-- SELECT pb.batch_flock_id, pb.production_type, pb.status, f.name as farm_name, ph.name as house_name
-- FROM poultry_batches pb
-- LEFT JOIN farms f ON pb.farm_id = f.id
-- LEFT JOIN poultry_houses ph ON pb.house_id = ph.id;

-- View recent egg collections:
-- SELECT ec.collection_date, ec.total_eggs_collected, ec.grade_a_quantity, pb.batch_flock_id
-- FROM egg_collections_enhanced ec
-- JOIN poultry_batches pb ON ec.batch_id = pb.id
-- ORDER BY ec.collection_date DESC;

